Regression examples
==================================================================================
author: Bernhard Angele
date: 22 September 2016

Question 1
===================================================================================
```{r}

ff <- y ~ x
mods <- setNames(as.list(1:4), paste0("lm", 1:4))
for(i in 1:4) {
  ff[2:3] <- lapply(paste0(c("y","x"), i), as.name)
  ## or   ff[[2]] <- as.name(paste0("y", i))
  ##      ff[[3]] <- as.name(paste0("x", i))
  mods[[i]] <- lmi <- lm(ff, data = anscombe)
  print(anova(lmi))
}

## See how close they are (numerically!)
sapply(mods, coef)
lapply(mods, function(fm) coef(summary(fm)))

## Now, do what you should have done in the first place: PLOTS
op <- par(mfrow = c(2, 2), mar = 0.1+c(4,4,1,1), oma =  c(0, 0, 2, 0))
for(i in 1:4) {
  ff[2:3] <- lapply(paste0(c("y","x"), i), as.name)
  plot(ff, data = anscombe, col = "red", pch = 21, bg = "orange", cex = 1.2,
       xlim = c(3, 19), ylim = c(3, 13))
  abline(mods[[i]], col = "blue")
}


d <- with(anscombe, data.frame(x = x1, y = y1))

write.csv(d, "practice_test_data_set_1.csv")

d <- with(anscombe, data.frame(x = x3, y = y3))
          
write.csv(d, "practice_test_data_set_2.csv")          

```

Question 4
===============================================
```{r}
with(anscombe, plot(, x = x1, y = y1 ,col = "red", pch = 21, bg = "orange", 
                    cex = 1.2, xlim = c(3, 19), ylim = c(3, 13)))
abline(lm(data = anscombe, y1 ~ x1), col = "red")
 
```


Question 6
===============================================
```{r}
with(anscombe, plot(, x = x3, y = y3 ,col = "red", pch = 21, bg = "orange", 
                    cex = 1.2, xlim = c(3, 19), ylim = c(3, 13)))
abline(lm(data = anscombe, y3 ~ x3), col = "red")
 
```