---
title: "Homework assignment 1"
author: "Your name here"
date: "Today's date"
output: html_document
---

## Assignment

We learned quite a bit about probability distributions today. The following R code demonstrates the Central Limit Theorem:

```{r, echo=T, fig.width = 14, fig.height = 6}
sample_size <- 100
number_of_simulations <- 1000

sample_means <- replicate(number_of_simulations, mean(rgamma(n = sample_size, shape = 3)))

hist(sample_means)
```

Write a short sentence or two explaining what is going on in the code chunk above. Then do the same thing sampling from a normal distribution (anyone you want) rather than the gamma distribution. 
*Hint:* The normal distribution doesn't have a `shape` parameter, but rather a `mean` and an `sd` parameter. 
*Hint 2:* The function you are looking for is `rnorm`.

Can you calculate the mean and the sd of your sample means? How are they related to the mean and sd of the original normal distribution you were sampling from?
Finally, what happens when you change the sample size? What happens when you change the number of simulations you run? Provide a few examples (code chunks plus outputs) and write a sentence or two. Copy and paste is your friend here (unlike elsewhere in academia!).

## Response

Replace this text with your response! Feel free to copy and paste the code chunk from above and then change as appropriate.