---
title: "Advanced Statistics Seminar 1"
author: "Is open science broken?"
date: "Press F for fullscreen"
output: 
  revealjs::revealjs_presentation:
    self_contained: true
    transition: fade
    css: "robot-lung.css"
  
---

# Introduction

- In the lecture, we have seen that psychology had and still has a problem with replicability.
- In this situation, as described, many psychologists looked to Open Science as a solution: Making methods, materials, data, and analyses transparent and publicly available.
- Open Science was inspired by the Open Source and Open Access movements
- But has it gone wrong? Is Open Science excluding scientists, especially those from non-privileged backgrounds?

# "#bropenscience"

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Thanks! Hopefully this thread &amp; many other similar discussions &amp; blogs will help make it less Bropen Science and more Open Science. \*hides\*</p>&mdash; Olivia Guest · Ολίβια Γκεστ (@o_guest) <a href="https://twitter.com/o_guest/status/871675631062458368?ref_src=twsrc%5Etfw">June 5, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


# The #bropenscience controversy

- In 2020, Guest wrote an article together with Kirstie Whitaker in The Psychologist, the official monthly publication of The British Psychological Society
- The discussion about bropenscience became very heated when some psychology researchers criticised a study by a PhD student, Roxanne Felig, in the British Journal of Social Psychology ([Felig et al., 2021](https://bpspsychub.onlinelibrary.wiley.com/doi/abs/10.1111/bjso.12489))

# The study

- Felig and her colleagues wanted to test the hypothesis that the apparent disregard for cold weather by women waiting outside nightclubs on cold nights is related to self-objectification.

# The tweets

- This resulted in many reactions by Twitter users concerned with Open Science and replicability, pointing out what they perceived as methodological issues with the paper:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">It&#39;s 2021 and social psychologists are still publishing papers like this: Women wearing not much clothing on a night out don&#39;t get cold because they believe that they &quot;look hot&quot; (geddit?)🧐🤦‍♂️🙄 <a href="https://twitter.com/EJWagenmakers?ref_src=twsrc%5Etfw">@EJWagenmakers</a> <a href="https://twitter.com/RolfZwaan?ref_src=twsrc%5Etfw">@RolfZwaan</a> <a href="https://twitter.com/lakens?ref_src=twsrc%5Etfw">@lakens</a> <a href="https://t.co/AgANDGrFAe">https://t.co/AgANDGrFAe</a> <a href="https://t.co/P8Wx1OAfnV">pic.twitter.com/P8Wx1OAfnV</a></p>&mdash; Nick Brown (@sTeamTraen) <a href="https://twitter.com/sTeamTraen/status/1458217774677954560?ref_src=twsrc%5Etfw">November 9, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

# The backlash
 
- Others pointed out that the criticism was quite harsh and perhaps not entirely justified
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">In my early days of Twitter before I started my postdoc, I was foolish and made fun of an article that I didn&#39;t read. The author (a female faculty) rightly confronted me and I apologized profusely. I learned my lesson. So I decided to read this article 1/n<a href="https://t.co/pgnVyro6mG">https://t.co/pgnVyro6mG</a></p>&mdash; Jin X. Goh | 吴晋勋 (@JinXunGoh) <a href="https://twitter.com/JinXunGoh/status/1458788716806348801?ref_src=twsrc%5Etfw">November 11, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

# The backlash

- But were they maybe also particularly motivated by the subject matter?
- Are there certain kinds of hypotheses that are particularly disliked by the defenders of open science?


# The backlash

- Amy Cuddy herself commented on the debate:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">1/ As psychological scientists begin to acknowledge the toxicity that developed in the &quot;methods revolution,&quot; I urge them to look back on critical moments &amp; decisions that were made early on and along the way, shaping what was to come.<br><br>To begin...</p>&mdash; Amy Cuddy, PhD (@amyjccuddy) <a href="https://twitter.com/amyjccuddy/status/1462895364126748676?ref_src=twsrc%5Etfw">November 22, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

# What now?

* Your task: In small groups (breakout rooms), *critically* read [the article by Whitaker and Guest](https://thepsychologist.bps.org.uk/volume-33/november-2020/bropenscience-broken-science) and consider the following questions.
* You should have an answer for each of the questions

# The questions

1. Imagine you read a research paper and you notice an error that makes the paper’s conclusion invalid. What do you do? What are the consequences? 
    + Would you publicly call out bad research practices even if it might damage another person’s career and wellbeing? 
    + Or, on the other hand, would you keep quiet about an error that might discredit a study or even a field because talking about it might expose the researchers to criticism and possibly abuse? 

# The questions

2. What is the purpose of research? Advance knowledge? Advance one’s career? Show that you are right? Show that others are wrong? 
    - Can we change the culture? How? 
    - Can we find a way to be both responsible with the conclusions that are made in our field and in the way we act towards the researchers who make these conclusions, even if we disagree? 

# The questions

3. Would you be less inclined to call out a researcher's error if the researcher is from a background that is severely underrepresented at universities?

4. What would you do if someone contacts you and tells you about an error in a study you published? What if they don’t just contact you, but make it public? 

# Answers?

- Take 20 minutes to talk about the questions. Then be ready to share the answers you came up with in your groups with everyone.
- There are no "correct" answers here, but, as you are future researchers, your attitudes towards this issue will shape what the field of psychology is like in the future.

# Conclusion

- Take a few minutes to consider:
    - Was there a consensus?
    - Did you attempt to appreciate both the perspective of the "open science bros" and the researchers who feel harassed and silenced by their criticism?
    - What should be the future of scientific discussion in Psychology?