---
title: "Advanced Statistics Homework 4: Picky cats"
author: "Bernhard Angele"
date: "23/10/2014"
output: pdf_document
---

### Scenario
A cat food manufacturer is interested in investigating how the fish and beef content of cat food affects the amount of food cats eat. The manufacturer would also like to know whether some breeds have different fish and beef preferences compared to other breeds. In order to do this, the manufacturer gave four different types of cat food to a group of 40 cats. Of the cats, there were 10 each of the following breeds: Shorthair, Persian, Siamese, and Manx. Of the four types of food, one type contained neither fish or beef, one type contained only fish, one type contained only beef, and one type contained both fish and beef. Over the course of four sessions (on four consecutive days), each cat was provided with an unlimited quantity of each food (a different food every day), with the researchers recording the amount of food each cat ate (in grammes) before wandering off to destroy the furniture, go to sleep, or annoy a human. How do fish and beef influence the amount of food eaten? Do the different cat breeds differ in terms of their beef and fish preferences?

### Assignment
Conduct and report the appropriate statistics as one would for an academic journal. Be sure to report the means, group sizes, and standard deviations in a table and to show all the significant effects in figures (Hint: you do not need to show non-significant effects). In addition, you should state whether there are any issues with the results (this may refer to assumption violations but other issues could also be mentioned) and how such problems might be overcome. Finally, in layperson (non-academic) language provide advice in terms of what you should be aware of when making cat food out of fish or beef.

### Due date
This homework will be due on **Thursday, October 30th at 1 pm** and should be submitted via myBU.

### Data
You can find the data in the table below. They are also available in the file `Assignment1_data.csv`.

```{r, echo=FALSE, results='asis'}
library(knitr)
data <- read.csv("Homework4_data.csv")[,-1]
colnames(data) <- c("Subject", "Fish", "Beef", "Breed", "Cat food eaten (in g)")
kable(data)
```