---
title: "Lecture 6 Seminar"
author: "Regression"
date: "Press F for fullscreen"
output: 
  revealjs::revealjs_presentation:
    self_contained: true
    transition: fade
    css: "robot-lung.css"
---  

# Using real data

- For this seminar, we will use a real, published data set from a study by [Kwiatkowska and Rogoza (2019)](https://www.sciencedirect.com/science/article/pii/S0191886919303162) (if you are not on campus, this link may not give you access -- in this case, you can access the [preprint](https://psyarxiv.com/a5vq2/).
- It is important to use data sets that reflect real research. This one falls into the personality/health psychology area.
- This is a study on the traits of *shyness* and *modesty* and how they fit into the Big 5 personality traits (e.g. Goldberg, 1999).
- The authors hypothesise that:
    - Shyness should be related to modesty (positively)
    - Shyness should be related to extraversion (negatively) and neuroticism (positively)
    - Modesty should be related to agreeableness (positively) and extraversion (again negatively)

# The data set: Shyness

- Online survey data from 727 Polish young adults (18--35 years old) recruited through Facebook
- Shyness measured using the Revised Cheek and Buss Shyness scale (RCBS, Cheek & Buss, 1981): 13 items, 5-point Likert scale

# The data set: Modesty
- Modesty measured using three scales:
    - Modest Responding Scale (MRS): 20 items, 7-point Likert scale
    - Modesty subscale of the International Personality Item Pool (IPIP) representation of the HEXACO personality inventory (IPIP HEXACO, Goldberg et al., 2006; Lee & Ashton, 2004): 10 items, 5-point Likert scale
    - Modesty subscale of the International Personality Item Pool (IPIP) representation of the NEO-PI-R personality inventory (IPIP NEO, Costa & McCrae, 1992; Goldberg et al., 2006): 10 items, 5-point Likert scale

# The data set: Big 5

- Big 5 personality traits: Big Five Inventory-2 (BFI2; Soto & John, 2017)
    - 60 items, 5-point Likert scale
    - Subscales:
        - Extraversion (BFI2-E)
        - Negative emotionality (neuroticism; BFI2-N)
        - Agreeableness (BFI2-A)
        - Conscientiousness (BFI2-C)
        - Openness (BFI2-O)

# Opening the data file

- Download the data file (bazka3.sav) from Brightspace and 

- Benjamin group: Look over the Benjamin et al. article: [Redefine Statistical Significance](https://www.nature.com/articles/s41562-017-0189-z)

- Find the main arguments that the authors are making. 
- Pay special attention to the potential objections.

# Preparing
- Lakens group: Look over the Benjamin et al. article: [Justify Your Alpha](https://www.diva-portal.org/smash/get/diva2:1194016/FULLTEXT01.pdf)
- Find the main arguments
- Pay special attention to the specific issues the authors identify with the proposal

# Preparing
- De Ruiter group: Look over the de Ruiter (2019) article: [Redefine or justify? Comments on the alpha debate](https://link.springer.com/article/10.3758/s13423-018-1523-9)
- Why is the author more on the side of Benjamin et al. than on the side of Lakens?
    - What are the rebuttals to each of Lakens et al.'s arguments?

# Preparing
- McShane group: [Abandon Statistial Significance](https://www.tandfonline.com/doi/full/10.1080/00031305.2018.1527253)
- What is the criticism of Benjamin et al.'s proposal?
- What is the alternative proposed?

# Debate

- Start with an introduction (one student per bullet point):
  - What is the issue? Why is there a need for change? (Benjamin group)
  - What is the proposal? (Benjamin Group)
  - What is wrong with the proposal? (Lakens group)
  - What is the issue with Lakens et al.'s proposal to "bring your own alpha"? (de Ruiter group)
  - What is wrong with the Benjamin et al. proposal from McShane et al.'s point of view?
- One argument per person
- Then continue with the debate, by default in the order Benjamin-Lakens-de Ruiter-McShane (but people can jump in!)
  
- Everybody should take notes: this is highly relevant for your assignment!